# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20171022_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='click_num',
            new_name='click_nums',
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%Y%m', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_position',
            field=models.CharField(max_length=50, verbose_name='公司职位'),
        ),
    ]
