# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20171022_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='click_nums',
            new_name='click_num',
        ),
    ]
